
ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS client_phone TEXT,
  ADD COLUMN IF NOT EXISTS client_email TEXT,
  ADD COLUMN IF NOT EXISTS obs TEXT,
  ADD COLUMN IF NOT EXISTS moto_brand TEXT,
  ADD COLUMN IF NOT EXISTS moto_model TEXT,
  ADD COLUMN IF NOT EXISTS moto_plate TEXT,
  ADD COLUMN IF NOT EXISTS moto_kms NUMERIC,
  ADD COLUMN IF NOT EXISTS moto_vin TEXT,
  ADD COLUMN IF NOT EXISTS retention BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE public.invoice_items
  ADD COLUMN IF NOT EXISTS discount NUMERIC NOT NULL DEFAULT 0;
